sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/runtime-nodejs:latest -t moussavdb/runtime-nodejs:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/runtime-nodejs
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/runtime-nodejs:latest;
    docker push moussavdb/runtime-nodejs:build_$TRAVIS_BUILD_NUMBER;
